<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <PackageId>JobGuardian.Abstractions</PackageId>

    <Description>
      Core abstractions, interfaces and contracts for JobGuardian, a cloud-native friendly framework
      for
      distributed job coordination, leader election and lease management.
      This package contains the public APIs required by JobGuardian implementations and extensions.
    </Description>

  </PropertyGroup>

</Project>