<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JobGuardian.Abstractions\JobGuardian.Abstractions.csproj" />
    <ProjectReference Include="..\JobGuardian.Core\JobGuardian.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>JobGuardian.PostgreSql</PackageId>

    <Description>
      PostgreSQL persistence provider for JobGuardian.
      Provides lease storage, ownership coordination and distributed state management for
      JobGuardian runtimes using PostgreSQL.
    </Description>

  </PropertyGroup>

</Project>